<?php 
    $cPrograms = array(
        "Hello World Program",
        "Add Two Numbers",
        "Check Even or Odd",
        "Find the Largest Number Among Three",
        "Swap Two Numbers",
        "Calculate Factorial of a Number",
        "Fibonacci Series",
        "Prime Number Check",
        "Reverse a Number",
        "Palindrome Check",
        "Calculate the Sum of Digits",
        "Decimal to Binary Conversion",
        "Binary to Decimal Conversion",
        "Basic Calculator",
        "Area of a Circle",
        "Area of a Rectangle",
        "Area of a Triangle",
        "Simple Interest Calculation",
        "Celsius to Fahrenheit Conversion",
        "Fahrenheit to Celsius Conversion",
        "Armstrong Number Check",
        "Perfect Number Check",
        "Print ASCII Value of a Character",
        "GCD (Greatest Common Divisor)",
        "LCM (Least Common Multiple)",
        "Factorization of a Number",
        "Reverse a String",
        "Count Vowels and Consonants in a String",
        "String Concatenation",
        "String Length Calculation",
        "Check for Anagrams",
        "Count Words in a Sentence",
        "Bubble Sort",
        "Selection Sort",
        "Insertion Sort",
        "Linear Search",
        "Binary Search",
        "Merge Sort",
        "Quick Sort",
        "Matrix Addition",
        "Matrix Subtraction",
        "Matrix Multiplication",
        "Transpose of a Matrix",
        "Check Upper Triangular Matrix",
        "Check Lower Triangular Matrix",
        "Pascal's Triangle",
        "Print Hollow Pyramid",
        "Print Number Pattern",
        "Print Floyd's Triangle",
        "Print Diamond Pattern",
        "Check Leap Year",
        "Print Calendar of a Month",
        "Find GCD and LCM of Array Elements",
        "Matrix Diagonal Sum",
        "Check for a Magic Square",
        // "Linked List Implementation",
        // "Stack Implementation",
        // "Queue Implementation",
        // "Circular Linked List Implementation",
        // "Binary Tree Traversal (Inorder, Preorder, Postorder)",
        // "Binary Search Tree (Insertion, Deletion, Search)",
        // "Depth-First Search (DFS) on a Graph",
        // "Breadth-First Search (BFS) on a Graph",
        // "Dijkstra's Algorithm",
        // "Prim's Algorithm",
        // "Kruskal's Algorithm",
        // "Convert Infix to Postfix Expression",
        // "Evaluate Postfix Expression",
        // "Check for Balanced Parentheses",
        // "Convert Decimal to Roman Numerals",
        // "Convert Roman Numerals to Decimal",
        // "Conversion of Units (e.g., Distance, Weight)",
        // "Basic File Operations (Read, Write, Copy)",
        // "Implement a Simple Shell",
        // "Basic Memory Allocation and Deallocation",
        // "Implement a Circular Queue",
        // "Implement a Priority Queue",
        // "Implement a Hash Table",
        // "Basic Socket Programming (Client-Server Interaction)",
        // "Producer-Consumer Problem (Multithreading)"
    );
?>